### PR TITLE
Ensure that Symbol can be used via bind

### LINKED ISSUE #19: Throwing error when called with a context that is not the global context
The following code should not throw according to the specification but does throw in this polyfill.

```js
Symbol.bind(Array)()
```

It is likely this section that is not working as expected:
https://github.com/es-shims/get-own-property-symbols/blob/fe7a6c86e9492bd197c9cfc151274cc5dba3d1fe/src/get-own-property-symbols.js#L96-L98

### PR DESCRIPTION
**Pull request by JakeChampion**
Fixes #19.

### CODE REVIEW

File: src/get-own-property-symbols.js [hunk 1]
```diff
@@ -93,7 +93,7 @@
       ));
     },
     Symbol = function Symbol(description) {
-      if (this && this !== G) {
+      if (this instanceof Symbol) {
```
Comment (ljharb) [inline src/get-own-property-symbols.js]: i assume this can't work cross-realm, but that's ok because it's a sham.

However, `Symbol.call(Symbol())` does not throw, so wouldn't this check make that fail?

Comment (JakeChampion) [reply src/get-own-property-symbols.js]: I added a testcase for this, it looks like it does not throw.

Comment (ljharb) [reply src/get-own-property-symbols.js]: I'm a bit confused; `function S() { if (this instanceof S) throw 42; return { __proto__: S.prototype }; } S.call(S())` throws. How is it possible that this doesn't?
